name: Junqi Logic Test

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        language: [python, node, java]
        python-version: [3.8, 3.9, 3.10]
        node-version: [16, 18]
        java-version: [17]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        if: matrix.language == 'python'
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Set up Node.js
        if: matrix.language == 'node'
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Dependencies
        if: matrix.language == 'python'
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
        if: matrix.language == 'node'
        run: npm install

      - name: Run Tests
        if: matrix.language == 'python'
        run: pytest
        if: matrix.language == 'node'
        run: npm test
