name: Junqi Logic Test

on:
  pull_request:
    branches:
      - main

jobs:
  test_python3_12_node23:
    runs-on: ubuntu-22.04

    defaults:
      run:
        working-directory: src/tests

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Set up Node.js 23.3.0
        uses: actions/setup-node@v3
        with:
          node-version: "23.3.0"

      - name: Install Python Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest

      - name: Install Node.js Dependencies
        run: npm install

      - name: Run Python Tests
        run: pytest

  test_python3_6_node18:
    runs-on: ubuntu-18.04

    defaults:
      run:
        working-directory: src/tests

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python 3.6.15
        uses: actions/setup-python@v4
        with:
          python-version: "3.6.15"

      - name: Set up Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install Python Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest

      - name: Install Node.js Dependencies
        run: npm install

      - name: Run Python Tests
        run: pytest