name: Junqi Logic Test

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-22.04
    
    defaults:
      run:
        working-directory: src/tests
        
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "23.3.0"

      - name: Install Python Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest

      - name: Install Node.js Dependencies
        run: npm install

      - name: Run Python Tests
        run: pytest
