name: Junqi Logic Test

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-22.04
    
    defaults:
      run:
        working-directory: src/tests
        
    strategy:
      matrix:
        language: [python, node]
        python-version: ["3.11", 3.12]
        node-version: [17, 18]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Python Dependencies
        if: matrix.language == 'python'
        run: |
          python -m pip install --upgrade pip
          pip install pytest

      - name: Install Node.js Dependencies
        if: matrix.language == 'node'
        run: npm install

      - name: Run Python Tests
        if: matrix.language == 'python'
        run: pytest
